from __future__ import annotations

import json
from pathlib import Path
from typing import Callable

from job_agent.agents.answer_cards import AnswerCardsAgent
from job_agent.agents.interview_prep import InterviewPrepAgent
from job_agent.atomic_io import atomic_write_text_batch
from job_agent.llm.harness import NodePolicy
from job_agent.nodes.answer_cards import render_answer_cards
from job_agent.nodes.mock_interview import (
    build_mock_interview_plan,
    render_mock_interview_plan,
)
from job_agent.nodes.interview_prep import render_interview_prep
from job_agent.schemas import EvidenceItem, FitVerdictResult, StructuredJD
from job_agent.session_orchestrator import (
    ARTIFACT_FILES,
    _parse_targeted_resume_markdown,
    write_session_state,
)

INTERVIEW_QUESTION_MAX_OUTPUT_TOKENS = 4096
ANSWER_CARD_MAX_OUTPUT_TOKENS = 8192


def _read_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def regenerate_interview_prep_live(
    session_dir: Path,
    runtime,
    *,
    progress_callback: Callable[[str], None] | None = None,
) -> tuple[str, ...]:
    session_dir = Path(session_dir)
    structured_jd = StructuredJD.model_validate(
        _read_json(session_dir / ARTIFACT_FILES["structured_jd"])
    )
    evidence = [
        EvidenceItem.model_validate(item)
        for item in (
            _read_json(session_dir / ARTIFACT_FILES["evidence_mapping"]) or []
        )
    ]
    fit_result = FitVerdictResult.model_validate(
        _read_json(session_dir / ARTIFACT_FILES["fit_verdict"])
    )
    targeted_resume = _parse_targeted_resume_markdown(
        (session_dir / ARTIFACT_FILES["targeted_resume"]).read_text(
            encoding="utf-8"
        ),
        structured_jd,
    )
    session_id = session_dir.name
    run_id = "ui-regenerate-interview-prep"
    question_policy = NodePolicy(
        allow_rule_fallback=False,
        max_output_tokens=INTERVIEW_QUESTION_MAX_OUTPUT_TOKENS,
    )
    answer_card_policy = NodePolicy(
        allow_rule_fallback=False,
        max_output_tokens=ANSWER_CARD_MAX_OUTPUT_TOKENS,
    )

    if progress_callback is not None:
        progress_callback("interview_prep")
    prep_result = InterviewPrepAgent(
        registry=runtime.registry,
        harness=runtime.harness,
        policy=question_policy,
    ).run(
        structured_jd,
        evidence=evidence,
        fit_result=fit_result,
        targeted_resume=targeted_resume,
        session_id=session_id,
        run_id=run_id,
    )
    if progress_callback is not None:
        progress_callback("answer_cards")
    cards_result = AnswerCardsAgent(
        registry=runtime.registry,
        harness=runtime.harness,
        policy=answer_card_policy,
    ).run(
        prep_result.value,
        evidence=evidence,
        targeted_resume=targeted_resume,
        session_id=session_id,
        run_id=run_id,
    )
    plan = build_mock_interview_plan(
        interview_prep=prep_result.value,
        answer_cards=cards_result.value,
    )

    prep_filename = ARTIFACT_FILES["interview_grilling"]
    cards_filename = ARTIFACT_FILES["answer_cards"]
    plan_filename = ARTIFACT_FILES["mock_interview_plan"]
    plan_path = session_dir / plan_filename
    previous_plan = (
        plan_path.read_text(encoding="utf-8") if plan_path.exists() else None
    )
    plan_markdown = render_mock_interview_plan(plan)
    atomic_write_text_batch(
        {
            session_dir / prep_filename: render_interview_prep(
                prep_result.value
            ),
            session_dir / cards_filename: render_answer_cards(
                cards_result.value
            ),
            plan_path: plan_markdown,
        }
    )

    invalidated_artifacts: dict[str, str] = {}
    if previous_plan != plan_markdown:
        for artifact_name in (
            "mock_interview_live",
            "mock_answers",
            "mock_debrief",
        ):
            stale_path = session_dir / ARTIFACT_FILES[artifact_name]
            if stale_path.exists():
                stale_path.unlink()
            invalidated_artifacts[artifact_name] = (
                "Invalidated because live interview preparation changed."
            )
    write_session_state(
        session_dir,
        fresh_artifacts={
            "interview_grilling": "Regenerated by the live interview-prep agent.",
            "answer_cards": "Regenerated by the live answer-cards agent.",
            "mock_interview_plan": "Rebuilt deterministically from live agent output.",
        },
        invalidated_artifacts=invalidated_artifacts,
        updated_by="ui_live_interview_prep",
    )
    return prep_filename, cards_filename, plan_filename
